#!/usr/bin/env python3
"""
statistical_tests.py
====================

Group-level statistical tests for the project
"Neural Dynamics of Object Recognition Under Sensory Uncertainty".

All hypothesis tests are implemented with **statsmodels** (preferred over
scipy / sklearn, per project convention):

H1 - Decoding accuracy is significantly above chance (0.5)
     -> One-sample t-test implemented as an OLS intercept test (sm.OLS).

H2 - Decoding accuracy decreases as sensory noise increases
     -> Linear mixed-effects model with per-subject random intercepts
        (smf.mixedlm), cross-checked with a cluster-robust OLS.

H3 - There is a "breaking point" (~40-50% noise) beyond which decoding
     falls back to chance
     -> Per-noise-bin one-sample tests against chance with multiple-comparison
        correction (statsmodels.stats.multitest.multipletests), plus a
        segmented (piecewise) regression breakpoint estimate (smf.ols).

H4 - Peak decoding latency is delayed as noise increases
     -> Linear mixed-effects model of peak_time on noise_center.

Expected input: two tidy pandas DataFrames
  * df_subject : one row per subject x noise bin
      columns: subject, channel, noise_bin, noise_min, noise_max,
               noise_center, peak_accuracy, peak_time
  * df_rep     : one row per subject x noise bin x MVPA repetition
      columns: subject, channel, noise_bin, noise_min, noise_max,
               noise_center, repetition, peak_accuracy, peak_time

These DataFrames are produced by `load_group_mvpa_results`, which reads the
`subject_*_results.pkl` files generated by main.py.
"""

import os
import pickle
from pathlib import Path

import numpy as np
import pandas as pd

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.multitest import multipletests

# ----------------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------------
CHANCE_LEVEL = 0.5          # chance decoding accuracy for 2 classes
DEFAULT_ALPHA = 0.05


# ----------------------------------------------------------------------------
# Data loading
# ----------------------------------------------------------------------------
def find_noise_result_dirs(base_dir="."):
    """
    Find MVPA result directories named like
    'mvpa_results - ecog - ... - noise0.00to0.20 - ...'.

    Returns
    -------
    dict : {(noise_min, noise_max): Path}
    """
    base_dir = Path(base_dir)
    noise_dirs = {}
    for dir_path in base_dir.glob("*noise*to*"):
        if not dir_path.is_dir():
            continue
        noise_parts = [p for p in dir_path.name.split(" - ") if "noise" in p]
        if not noise_parts:
            continue
        try:
            range_str = noise_parts[0].replace("noise", "")
            lo, hi = range_str.split("to")
            noise_dirs[(float(lo), float(hi))] = dir_path
        except ValueError:
            continue
    return dict(sorted(noise_dirs.items()))


def load_group_mvpa_results(base_dir=".", source="all_channels",
                            min_peak_time=None):
    """
    Load all saved MVPA results (subject_*_results.pkl) produced by main.py
    and assemble tidy group-level DataFrames.

    Parameters
    ----------
    base_dir : str or Path
        Directory containing the '...noiseX.XXtoY.YY...' result folders.
    source : {'all_channels', 'single_channels', 'both'}
        Which decoding results to extract.
    min_peak_time : float or None
        If given (e.g. 0.0), peak accuracy / peak latency of every curve are
        searched only among windows at or after this time (ms). Use 0.0 to
        exclude the pre-stimulus baseline from the peak search: the decoder
        runs over the whole -200..500 ms window, so in high-noise conditions a
        noisy baseline window can otherwise win the argmax and be reported as
        the "peak". Defaults to None = keep the original full-window peaks.

    Returns
    -------
    (df_subject, df_rep) : tuple of pandas.DataFrame, or None if no results
        files were found.
    """
    noise_dirs = find_noise_result_dirs(base_dir)
    if not noise_dirs:
        print(f"No MVPA result directories found under: {base_dir}")
        return None

    subj_rows, rep_rows = [], []

    for (noise_min, noise_max), dir_path in noise_dirs.items():
        noise_center = 0.5 * (noise_min + noise_max)
        noise_bin = f"{noise_min:.1f}-{noise_max:.1f}"

        for results_file in sorted(dir_path.glob("subject_*_results.pkl")):
            try:
                with open(results_file, "rb") as f:
                    subject_data = pickle.load(f)
            except Exception as e:
                print(f"  ! Could not load {results_file}: {e}")
                continue

            subject_idx = subject_data.get("subject_idx")
            if subject_idx is None:
                try:
                    subject_idx = int(results_file.stem.split("_")[1])
                except (IndexError, ValueError):
                    subject_idx = -1

            # Collect the per-channel / all-channel result dicts of interest
            selected = {}
            if source in ("all_channels", "both") and subject_data.get("all_channels_result"):
                selected["ALL_CHANNELS"] = subject_data["all_channels_result"]
            if source in ("single_channels", "both"):
                selected.update(subject_data.get("channel_results", {}) or {})

            for ch_name, r in selected.items():
                all_acc = np.asarray(r["all_accuracies"])      # (n_reps, n_windows)
                times = np.asarray(r["window_times"])

                # Peak-search mask (all True -> original full-window behaviour).
                if min_peak_time is None:
                    mask = np.ones(times.shape, dtype=bool)
                else:
                    mask = times >= min_peak_time
                if not mask.any():          # never leave the search empty
                    mask = np.ones(times.shape, dtype=bool)
                peak_times = times[mask]

                mean_curve = all_acc.mean(axis=0)
                subj_peak_idx = int(np.argmax(mean_curve[mask]))

                subj_rows.append({
                    "subject": subject_idx,
                    "channel": ch_name,
                    "noise_bin": noise_bin,
                    "noise_min": noise_min,
                    "noise_max": noise_max,
                    "noise_center": noise_center,
                    "peak_accuracy": float(mean_curve[mask].max()),
                    "peak_time": float(peak_times[subj_peak_idx]),
                })

                for rep_idx in range(all_acc.shape[0]):
                    rep_acc = all_acc[rep_idx][mask]
                    rep_peak_idx = int(np.argmax(rep_acc))
                    rep_rows.append({
                        "subject": subject_idx,
                        "channel": ch_name,
                        "noise_bin": noise_bin,
                        "noise_min": noise_min,
                        "noise_max": noise_max,
                        "noise_center": noise_center,
                        "repetition": rep_idx,
                        "peak_accuracy": float(np.max(rep_acc)),
                        "peak_time": float(peak_times[rep_peak_idx]),
                    })

    if not subj_rows:
        print("Result directories were found but contained no usable data.")
        return None

    df_subject = pd.DataFrame(subj_rows)
    df_rep = pd.DataFrame(rep_rows)
    print(f"Loaded {len(df_subject)} subject-level and {len(df_rep)} "
          f"repetition-level observations from {len(noise_dirs)} noise bins.")
    return df_subject, df_rep


def simulate_group_dataset(n_subjects=7, n_repetitions=10, seed=42):
    """
    Simulate a group-level dataset with exactly the schema returned by
    `load_group_mvpa_results`.

    This is only a clearly-labelled FALLBACK so the statistical pipeline can be
    demonstrated when the `main.py` output folders are absent. Generative model
    (per subject x noise bin):

      * peak decoding accuracy decays sigmoidally from ~0.80 at noise 0.1
        towards chance (0.5) at high noise, with a subject-specific gain;
      * peak latency increases roughly linearly with noise
        (~150 ms + 260 ms per unit noise, subject-specific offset);
      * each MVPA repetition is an accuracy bump over time plus noise, so
        `df_rep` mimics the real pipeline (per-repetition argmax peaks) while
        `df_subject` uses the repetition-averaged curve, as utils.py does.

    Returns
    -------
    (df_subject, df_rep) : tuple of pandas.DataFrame
    """
    rng = np.random.default_rng(seed)
    noise_edges = np.linspace(0.0, 1.0, 6)          # 5 noise bins
    times = np.arange(-175.0, 476.0, 10.0)          # window centres (ms)

    subj_rows, rep_rows = [], []
    for subject in range(n_subjects):
        gain = 1.0 + rng.normal(0.0, 0.15)
        latency_offset = rng.normal(0.0, 15.0)

        for lo, hi in zip(noise_edges[:-1], noise_edges[1:]):
            c = 0.5 * (lo + hi)
            noise_bin = f"{lo:.1f}-{hi:.1f}"
            # Sigmoid decay of the decoding bump above a slightly sub-chance
            # baseline: the real decoder sits a little below 0.5 on windows
            # that carry no category signal, which is why the real high-noise
            # peaks land near (just under) chance rather than at 0.5 + noise.
            baseline = 0.5 - 0.03 * gain
            amplitude = gain * 0.30 / (1.0 + np.exp((c - 0.45) / 0.08))
            true_latency = 150.0 + 260.0 * c + latency_offset

            curves = np.empty((n_repetitions, times.size))
            for rep in range(n_repetitions):
                curve = baseline + amplitude * np.exp(
                    -0.5 * ((times - true_latency) / 150.0) ** 2)
                curve = np.clip(curve + rng.normal(0.0, 0.03, times.size),
                                0.2, 1.0)
                curves[rep] = curve
                rep_rows.append({
                    "subject": subject, "channel": "ALL_CHANNELS",
                    "noise_bin": noise_bin, "noise_min": lo, "noise_max": hi,
                    "noise_center": c, "repetition": rep,
                    "peak_accuracy": float(curve.max()),
                    "peak_time": float(times[int(curve.argmax())]),
                })

            mean_curve = curves.mean(axis=0)
            subj_rows.append({
                "subject": subject, "channel": "ALL_CHANNELS",
                "noise_bin": noise_bin, "noise_min": lo, "noise_max": hi,
                "noise_center": c,
                "peak_accuracy": float(mean_curve.max()),
                "peak_time": float(times[int(mean_curve.argmax())]),
            })

    df_subject = pd.DataFrame(subj_rows)
    df_rep = pd.DataFrame(rep_rows)
    print(f"Simulated {len(df_subject)} subject-level and {len(df_rep)} "
          f"repetition-level observations from {n_subjects} subjects x "
          f"{len(noise_edges) - 1} noise bins x {n_repetitions} repetitions.")
    return df_subject, df_rep


# ----------------------------------------------------------------------------
# Core statistical helpers (statsmodels)
# ----------------------------------------------------------------------------
def one_sided_p(p_two_sided, estimate, direction="greater"):
    """
    Convert a two-sided p-value into a one-sided p-value.

    direction='greater' tests H1: estimate > 0
    direction='less'    tests H1: estimate < 0
    """
    if direction == "greater":
        return p_two_sided / 2.0 if estimate > 0 else 1.0 - p_two_sided / 2.0
    elif direction == "less":
        return p_two_sided / 2.0 if estimate < 0 else 1.0 - p_two_sided / 2.0
    raise ValueError("direction must be 'greater' or 'less'")


def one_sample_test(values, test_value=CHANCE_LEVEL):
    """
    One-sample t-test against `test_value`, implemented with statsmodels OLS:
    regress (values - test_value) on a constant; the intercept t-test is
    exactly the one-sample t-test.

    Returns
    -------
    dict with n, mean, sd, t, df, p_two_sided, p_greater, p_less, ci_low, ci_high
    """
    values = np.asarray(values, dtype=float)
    values = values[~np.isnan(values)]
    n = len(values)

    if n < 3:
        return {"n": n, "mean": np.nan, "sd": np.nan, "t": np.nan,
                "df": np.nan, "p_two_sided": np.nan, "p_greater": np.nan,
                "p_less": np.nan, "ci_low": np.nan, "ci_high": np.nan}

    diff = values - test_value
    res = sm.OLS(diff, np.ones((n, 1))).fit()

    t_stat = float(res.tvalues[0])
    p_two = float(res.pvalues[0])
    ci = res.conf_int()[0]

    return {
        "n": n,
        "mean": float(np.mean(values)),
        "sd": float(np.std(values, ddof=1)),
        "t": t_stat,
        "df": n - 1,
        "p_two_sided": p_two,
        "p_greater": one_sided_p(p_two, t_stat, "greater"),
        "p_less": one_sided_p(p_two, t_stat, "less"),
        "ci_low": float(ci[0] + test_value),
        "ci_high": float(ci[1] + test_value),
    }


# ----------------------------------------------------------------------------
# H1: decoding above chance
# ----------------------------------------------------------------------------
def h1_above_chance(df_subject, value_col="peak_accuracy",
                    chance=CHANCE_LEVEL):
    """
    H1: For each noise bin (and pooled across all bins), test whether decoding
    accuracy is significantly above chance across subjects.

    Note on the pooled 'ALL' row: each subject first contributes its mean
    accuracy across noise bins, so the test runs on one independent observation
    per subject. Testing every subject x bin row directly would
    pseudo-replicate subjects and understate the standard error (inflated df).

    Returns a tidy DataFrame of test results.
    """
    rows = []
    for noise_bin, grp in df_subject.groupby("noise_bin", sort=False):
        r = one_sample_test(grp[value_col].values, chance)
        r.update({"noise_bin": noise_bin,
                  "noise_center": grp["noise_center"].iloc[0]})
        rows.append(r)

    # Pooled test: one observation per subject (mean over that subject's bins).
    per_subject = df_subject.groupby("subject")[value_col].mean()
    r_all = one_sample_test(per_subject.values, chance)
    r_all.update({"noise_bin": "ALL", "noise_center": np.nan})
    rows.append(r_all)

    out = pd.DataFrame(rows)
    cols = ["noise_bin", "noise_center", "n", "mean", "sd", "t", "df",
            "p_greater", "p_two_sided", "ci_low", "ci_high"]
    return out[cols].sort_values("noise_center", na_position="last")


# ----------------------------------------------------------------------------
# H2: accuracy decreases with noise (mixed-effects)
# ----------------------------------------------------------------------------
def h2_accuracy_trend(df_rep, chance=CHANCE_LEVEL):
    """
    H2: Test whether decoding accuracy decreases with noise.

    Primary model: linear mixed-effects model with per-subject random
    intercepts on the repetition-level data:
        (peak_accuracy - chance) ~ noise_center + (1 | subject)
    Sensitivity check: OLS with cluster-robust (subject-level) standard errors.

    Returns
    -------
    dict with 'mixed' (MixedLMResults), 'ols' (OLSResults) and scalar summaries
    """
    df = df_rep.copy()
    df["acc_vs_chance"] = df["peak_accuracy"] - chance

    mixed = smf.mixedlm("acc_vs_chance ~ noise_center", df,
                        groups=df["subject"]).fit(reml=False)
    ols = smf.ols("acc_vs_chance ~ noise_center", df).fit(
        cov_type="cluster", cov_kwds={"groups": df["subject"]})

    slope_mixed = float(mixed.params["noise_center"])
    p_mixed = float(mixed.pvalues["noise_center"])
    slope_ols = float(ols.params["noise_center"])
    p_ols = float(ols.pvalues["noise_center"])

    return {
        "mixed": mixed,
        "ols": ols,
        "slope_mixed": slope_mixed,
        "p_mixed_two_sided": p_mixed,
        "p_mixed_decrease": one_sided_p(p_mixed, slope_mixed, "less"),
        "slope_ols": slope_ols,
        "p_ols_two_sided": p_ols,
        "p_ols_decrease": one_sided_p(p_ols, slope_ols, "less"),
    }


# ----------------------------------------------------------------------------
# H3: breaking point
# ----------------------------------------------------------------------------
def h3_adjacent_bin_paired_tests(df_subject, alpha=DEFAULT_ALPHA,
                                 correction="fdr_bh"):
    """
    H3 complementary test: paired t-tests between consecutive noise bins.

    For each adjacent pair of noise bins (sorted by noise_center), a paired
    t-test is computed on subject-level peak_accuracy values (each subject
    contributes one observation per bin). This directly identifies where the
    significant accuracy drop occurs.

    Subjects are matched by index (`subject`) before pairing. main.py can skip
    subjects whose data failed to load, so bins may have different subject sets;
    pairing positionally would then silently compare different subjects.

    Returns
    -------
    DataFrame with columns: bin_low, bin_high, n, t, df, p_two_sided,
    p_corrected, significant
    """
    bins_sorted = df_subject.sort_values("noise_center")["noise_bin"].unique()
    rows = []
    for i in range(len(bins_sorted) - 1):
        low_bin, high_bin = bins_sorted[i], bins_sorted[i + 1]
        low = (df_subject[df_subject["noise_bin"] == low_bin]
               .set_index("subject")["peak_accuracy"])
        high = (df_subject[df_subject["noise_bin"] == high_bin]
                .set_index("subject")["peak_accuracy"])
        # Inner join on subject -> keep only subjects present in both bins.
        paired = pd.concat({"low": low, "high": high}, axis=1,
                           join="inner").dropna()
        if len(paired) < 3:
            continue
        diff = (paired["low"] - paired["high"]).to_numpy()
        res = sm.OLS(diff, np.ones((len(diff), 1))).fit()
        rows.append({
            "bin_low": low_bin, "bin_high": high_bin,
            "n": int(len(diff)),
            "t": float(res.tvalues[0]), "df": int(len(diff) - 1),
            "p_two_sided": float(res.pvalues[0]),
        })

    table = pd.DataFrame(rows)
    if len(table) == 0:
        return table

    rej, adj, _, _ = multipletests(table["p_two_sided"].to_numpy(),
                                   alpha=alpha, method=correction)
    table["p_corrected"] = adj
    table["significant"] = rej
    return table


def h3_breaking_point(df_subject, alpha=DEFAULT_ALPHA, chance=CHANCE_LEVEL,
                      correction="fdr_bh"):
    """
    H3: Identify the noise level beyond which decoding is no longer above
    chance ("breaking point").

    1. One-sample test vs. chance for every noise bin (across subjects).
    2. Correct the bin-wise p-values for multiple comparisons
       (default: Benjamini-Hochberg FDR; use 'bonferroni' for a stricter test).
    3. Breaking point = midpoint between the last significant bin center and
       the first non-significant bin center.

    Returns
    -------
    dict with 'table' (DataFrame) and 'breaking_point' (float or None)
    """
    rows = []
    for noise_bin, grp in df_subject.groupby("noise_bin", sort=False):
        r = one_sample_test(grp["peak_accuracy"].values, chance)
        r.update({"noise_bin": noise_bin,
                  "noise_center": grp["noise_center"].iloc[0]})
        rows.append(r)

    table = pd.DataFrame(rows).sort_values("noise_center").reset_index(drop=True)

    pvals = table["p_greater"].to_numpy()
    valid = ~np.isnan(pvals)
    reject = np.zeros(len(pvals), dtype=bool)
    p_adj = np.full(len(pvals), np.nan)
    if valid.sum() > 0:
        rej_v, adj_v, _, _ = multipletests(pvals[valid], alpha=alpha,
                                           method=correction)
        reject[valid] = rej_v
        p_adj[valid] = adj_v

    table["p_corrected"] = p_adj
    table["significant"] = reject

    # Breaking point: transition from significant to non-significant
    breaking_point = None
    sig_centers = table.loc[table["significant"], "noise_center"].to_numpy()
    nonsig_centers = table.loc[~table["significant"], "noise_center"].to_numpy()
    if len(sig_centers) > 0 and len(nonsig_centers) > 0:
        last_sig = sig_centers.max()
        first_nonsig = nonsig_centers[nonsig_centers > last_sig]
        if len(first_nonsig) > 0:
            breaking_point = 0.5 * (last_sig + first_nonsig.min())
        else:
            breaking_point = last_sig

    return {"table": table, "breaking_point": breaking_point,
            "correction": correction, "alpha": alpha}


def estimate_breakpoint(df, value_col="peak_accuracy", n_candidates=25):
    """
    Estimate the breaking point with a segmented (piecewise linear) regression
    fitted by OLS (statsmodels):

        y ~ noise_center + max(noise_center - bp, 0)

    The breakpoint `bp` is selected by grid search minimizing AIC; the 'hinge'
    term's p-value tests whether the slope change is significant. Standard
    errors are cluster-robust at the subject level (repetition-level rows are
    correlated within subjects), matching the sensitivity checks in H2/H4.
    AIC is likelihood-based and therefore unaffected by the robust covariance.

    Returns
    -------
    dict with 'breakpoint', 'aic', 'hinge_coef', 'hinge_p', 'fit', 'comparison'
    """
    df = df.dropna(subset=[value_col, "noise_center"]).copy()
    lo, hi = df["noise_center"].quantile([0.15, 0.85])
    candidates = np.linspace(lo, hi, n_candidates)

    best = None
    comparison = []
    for bp in candidates:
        # Build the hinge for THIS candidate in a fresh frame. NOTE: do not
        # mutate `df` itself -- the stored results must reference the hinge
        # values of the candidate they describe, not whatever the loop
        # writes last.
        cand_df = df.copy()
        cand_df["hinge"] = np.maximum(cand_df["noise_center"] - bp, 0.0)
        if cand_df["hinge"].nunique() < 2:
            continue
        fit = smf.ols(f"{value_col} ~ noise_center + hinge", cand_df).fit(
            cov_type="cluster", cov_kwds={"groups": cand_df["subject"]})
        cand_hinge_p = float(fit.pvalues["hinge"])
        comparison.append({"candidate_bp": bp, "aic": fit.aic,
                           "hinge_p": cand_hinge_p})
        if best is None or fit.aic < best["aic"]:
            best = {"breakpoint": float(bp), "aic": float(fit.aic),
                    "hinge_coef": float(fit.params["hinge"]),
                    "hinge_p": cand_hinge_p, "fit": fit}

    if best is None:
        return {"breakpoint": None}

    # Linear (no-break) reference model for comparison
    fit_linear = smf.ols(f"{value_col} ~ noise_center", df).fit()
    best["aic_linear_model"] = float(fit_linear.aic)
    best["comparison"] = pd.DataFrame(comparison)
    return best


# ----------------------------------------------------------------------------
# H4: latency delay
# ----------------------------------------------------------------------------
def h4_latency_trend(df_rep):
    """
    H4: Test whether peak decoding latency increases with noise.

    Mixed-effects model with per-subject random intercepts:
        peak_time ~ noise_center + (1 | subject)
    Plus a cluster-robust OLS sensitivity check.

    Returns
    -------
    dict with 'mixed', 'ols' and scalar summaries
    """
    df = df_rep.copy()

    mixed = smf.mixedlm("peak_time ~ noise_center", df,
                        groups=df["subject"]).fit(reml=False)
    ols = smf.ols("peak_time ~ noise_center", df).fit(
        cov_type="cluster", cov_kwds={"groups": df["subject"]})

    slope_mixed = float(mixed.params["noise_center"])
    p_mixed = float(mixed.pvalues["noise_center"])
    slope_ols = float(ols.params["noise_center"])
    p_ols = float(ols.pvalues["noise_center"])

    return {
        "mixed": mixed,
        "ols": ols,
        "slope_mixed": slope_mixed,              # ms per unit noise (0-1)
        "p_mixed_two_sided": p_mixed,
        "p_mixed_increase": one_sided_p(p_mixed, slope_mixed, "greater"),
        "slope_ols": slope_ols,
        "p_ols_two_sided": p_ols,
        "p_ols_increase": one_sided_p(p_ols, slope_ols, "greater"),
    }


# ----------------------------------------------------------------------------
# Convenience: run everything
# ----------------------------------------------------------------------------
def _h3_cliff_row(h3_pairs, col):
    """Return the value of `col` for the last significant adjacent-bin drop
    (the 'cliff'), or NaN if no significant drop exists."""
    if len(h3_pairs) == 0:
        return np.nan
    sig = h3_pairs[h3_pairs["significant"]]
    if len(sig) == 0:
        return np.nan
    return float(sig.iloc[-1][col])


def run_all_tests(df_subject, df_rep, alpha=DEFAULT_ALPHA, chance=CHANCE_LEVEL,
                  correction="fdr_bh"):
    """
    Run all four hypothesis tests and return (results_dict, summary_df).
    """
    results = {
        "h1": h1_above_chance(df_subject, chance=chance),
        "h2": h2_accuracy_trend(df_rep, chance=chance),
        "h3": h3_breaking_point(df_subject, alpha=alpha, chance=chance,
                                correction=correction),
        "h3_pairs": h3_adjacent_bin_paired_tests(df_subject, alpha=alpha,
                                                 correction=correction),
        "h3_breakpoint_fit": estimate_breakpoint(df_rep),
        "h4": h4_latency_trend(df_rep),
    }

    h2 = results["h2"]
    h3 = results["h3"]
    h3_pairs = results["h3_pairs"]
    bp = results["h3_breakpoint_fit"]
    h4 = results["h4"]

    summary_rows = [
        {"hypothesis": "H1: accuracy > chance (lowest noise bin)",
         "test": "one-sample t (OLS intercept)",
         "statistic": results["h1"]["t"].iloc[0],
         "p_value": results["h1"]["p_greater"].iloc[0]},
        {"hypothesis": "H2: accuracy decreases with noise",
         "test": "mixed-effects model (slope)",
         "statistic": h2["slope_mixed"],
         "p_value": h2["p_mixed_decrease"]},
        {"hypothesis": f"H3: breaking point ({h3['correction']})",
         "test": "per-bin tests + corrected p-values",
         "statistic": h3["breaking_point"],
         "p_value": np.nan},
        {"hypothesis": "H3: accuracy drop at cliff (adjacent bins)",
         "test": "paired t-test, FDR-corrected",
         "statistic": _h3_cliff_row(h3_pairs, "t"),
         "p_value": _h3_cliff_row(h3_pairs, "p_corrected")},
        {"hypothesis": "H3: slope change at breakpoint",
         "test": "segmented regression (hinge term)",
         "statistic": bp.get("hinge_coef", np.nan),
         "p_value": bp.get("hinge_p", np.nan)},
        {"hypothesis": "H4: peak latency increases with noise",
         "test": "mixed-effects model (slope)",
         "statistic": h4["slope_mixed"],
         "p_value": h4["p_mixed_increase"]},
    ]
    summary = pd.DataFrame(summary_rows)
    summary["significant"] = summary["p_value"] < alpha
    return results, summary
